import React from 'react';
import type { BenchmarkSession } from '../../benchmark/engine/types';

interface PrintableReportProps {
  session: BenchmarkSession;
}

/**
 * A visually simplified, strictly structured layout meant only for printing.
 * This component is hidden from the screen via CSS (print:block hidden) 
 * or similar tailwind classes. When window.print() is called, this layout
 * takes over the page.
 */
export const PrintableReport: React.FC<PrintableReportProps> = ({ session }) => {
  const date = new Date(session.completedAt).toLocaleString();

  // Sort results by execution time (fastest first)
  const sortedResults = [...session.results].sort((a, b) => a.executionTimeMs - b.executionTimeMs);

  return (
    <div className="hidden print:block absolute inset-0 bg-white text-black p-8 font-sans">
      <div className="border-b-2 border-black pb-4 mb-6">
        <h1 className="text-3xl font-bold">Benchmark Report</h1>
        <div className="flex justify-between text-sm text-gray-600 mt-2">
          <span>Generated: {date}</span>
          <span>Session ID: {session.id.substring(0, 8)}</span>
        </div>
      </div>

      <div className="mb-8">
        <h2 className="text-xl font-semibold mb-3 border-b border-gray-300 pb-1">Configuration</h2>
        <div className="grid grid-cols-2 gap-4 text-sm">
          <div><strong>Dataset Type:</strong> {session.config.datasetType}</div>
          <div><strong>Dataset Sizes:</strong> {session.config.datasetSizes.join(', ')} items</div>
          <div><strong>Warmup Iterations:</strong> {session.config.warmupIterations ?? 1}</div>
        </div>
      </div>

      <div>
        <h2 className="text-xl font-semibold mb-3 border-b border-gray-300 pb-1">Algorithm Results</h2>
        <table className="w-full text-sm border-collapse">
          <thead>
            <tr className="bg-gray-100 border-b border-gray-400 text-left">
              <th className="p-2">Algorithm</th>
              <th className="p-2 text-right">Time (ms)</th>
              <th className="p-2 text-right">Comparisons</th>
              <th className="p-2 text-right">Swaps</th>
              <th className="p-2 text-right">Memory (Bytes)</th>
              <th className="p-2 text-center">Valid</th>
            </tr>
          </thead>
          <tbody>
            {sortedResults.map((r, i) => (
              <tr key={r.algorithmId} className={i % 2 === 0 ? 'bg-white' : 'bg-gray-50'}>
                <td className="p-2 border-b border-gray-200">{r.algorithmName}</td>
                <td className="p-2 border-b border-gray-200 text-right font-mono">{r.executionTimeMs.toFixed(3)}</td>
                <td className="p-2 border-b border-gray-200 text-right font-mono">{r.comparisons.toLocaleString()}</td>
                <td className="p-2 border-b border-gray-200 text-right font-mono">{r.swaps.toLocaleString()}</td>
                <td className="p-2 border-b border-gray-200 text-right font-mono">{r.memoryEstimateBytes.toLocaleString()}</td>
                <td className="p-2 border-b border-gray-200 text-center">{r.correct ? 'Yes' : 'No'}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <div className="mt-12 text-center text-xs text-gray-400">
        <p>Generated by Sorting Algorithm Benchmark Web App v1.0.0</p>
      </div>
    </div>
  );
};
